#ifndef OMNIROTACMDVALUES_HPP
#define OMNIROTACMDVALUES_HPP
  #define OMNIROTA_CMD_POWER_ON 0x01
  #define OMNIROTA_CMD_POWER_OFF 0x02
  #define OMNIROTA_CMD_MC_ON 0x03
  #define OMNIROTA_CMD_MC_OFF 0x04
  #define OMNIROTA_CMD_GET_CURRENT 0x05
  #define OMNIROTA_CMD_GET_SPEED 0x06
  #define OMNIROTA_CMD_SET_SPEED 0x07
  #define OMNIROTA_CMD_GET_TEMP 0x08
  #define OMNIROTA_CHECK_DCLINK_VTG 0x09
  #define OMNIROTA_CHECK_INVERTER_PWR 0x0A
  #define OMNIROTA_INVERTER_UPTIME 0x0c
  #define OMNIROTA_GET_PWR_STAGE_STATUS 0x0D
  #define OMNIROTA_CMD_HEARTBEAT 0xA0
  #define OMNIROTA_CMD_HEARTBEAT_VAL 0x0F
  #define OMNIROTA_CMD_TURN 0x0F
  
  #define OMNIROTA_DRIVING_MOTOR_SEND 0x101
  #define OMNIROTA_DRIVING_MOTOR_RECV 0x102
  #define OMNIROTA_STEERING_MOTOR_SEND 0x103
  #define OMNIROTA_STEERING_MOTOR_RECV 0x104
  
  #define OMNIROTA_MOTOR_DIRECTION_FORWARD 1
  #define OMNIROTA_MOTOR_DIRECTION_BACKWARD 2
#endif //OMNIROTACMDVALUES_HPP
